### ISSUE TITLE
WebSocket opening handshake was canceled

### ISSUE THREAD

**Issue by mgochoa** [SanMi86/HelloWorld#2]
I get this on my phone when trying to reach the connection with the server from the Ionic app on Android.
`main.js:76370 WebSocket connection to 'wss://10.180.40.52:8440/helloworld' failed: WebSocket opening handshake was canceled`

 Then I got this:
`_main.js:76534 WebSocket is already in CLOSING or CLOSED state.`

My _server.js_ file is configured like this: 

````javascript 
var argv = minimist(process.argv.slice(2), {
    default: {
        as_uri: 'https://localhost:8440',
        ws_uri: 'wss://KMS_SERVER:8888/kurento'
    }
});
````
And my ionic project _video.ts_ is configured like this:
```javascript
var ws = new WebSocket('wss://10.180.40.52:8440/helloworld');
```

My public ip on my network is _10.180.40.52_ . So I don´t understand why it's not working.

I'm sorry, I'm a little bit new on this Kurento/WebRTC world.

**Comment by SanMi86** [comment]
First at all sorry for my english.

the "as_uri" variable is the url where the server will be up, for that you should configured the websocket at video.ts with the same IP.

You have two options:

1. localhost:

- server.js

```
var argv = minimist(process.argv.slice(2), {
    default: {
        as_uri: 'https://localhost:8440',
        ws_uri: 'wss://KMS_SERVER:8888/kurento'
    }
});
```

- video.ts

`var ws = new WebSocket('wss://localhost:8440/helloworld');`

2. public ip:

- server.js

```
var argv = minimist(process.argv.slice(2), {
    default: {
        as_uri: 'https://10.180.40.52:8440',
        ws_uri: 'wss://KMS_SERVER:8888/kurento'
    }
});
```

- video.ts

`var ws = new WebSocket('wss://10.180.40.52:8440/helloworld');`

The most simple to started and to learn is with localhost because you will not have the possible problems with NAT and router configuration

**Comment by mgochoa** [comment]
I'm trying this. But I think my problem is because certificates and SSL.

**Comment by mgochoa** [comment]
I'm closing this issue, It was SSL and certificate problems on my node server. I had to mount it with Https and now it connects well, but I can't run HelloWorld example on mobile yet.

**Comment by mgochoa** [comment]
For your information, I could make my application to join a room, but not recording yet.
